### PR TITLE
Add Logo Upload Functionality for Experience, Education, and Skill Objects

### LINKED ISSUE #2: Allow logos to be stored for each object
All Experience, Education and Skill objects contain a logo attribute. Figure out a way to store these images with user friendliness in mind.

The client should identify if the logo field is empty and display this field.

### PR DESCRIPTION
**Pull request by hastagAB**
closes #2 

Add functionality to upload and store logos for Experience, Education, and Skill objects in the `uploads/` directory. 

- Add logo upload handling for all relevant POST endpoints (/resume/experience, /resume/education, /resume/skill).
- Upload logos are securely stored in the uploads/ directory. If no logo is provided, a default logo `(default.jpg)` is used.
- Update the Experience, Education, and Skill models to include the logo attribute.

### CODE REVIEW

**Comment by hastagAB** [comment]
@Pradyuman7 Please review the PR

**Comment by awilkescom** [comment]
Looks good @hastagAB  - can you resolve the conflict and we can merge?

**Comment by hastagAB** [comment]
@awilkescom Resolved. Please merge!

**Comment by awilkescom** [comment]
Great, good work!

**Comment by larrytamnjong** [comment]
Hi @hastagAB I'm trying to upload an image from the frontend to the backend, and while the form data seems to be coming through, I'm consistently receiving a 415 error from the /resume/experience endpoint. I've logged the payload from the frontend and attached a screenshot. Could you take a look and let me know if you have any insights on this?
image

**Comment by hastagAB** [comment]
Hi @larrytamnjong, try with `multipart/form-data` in all cases. Make sure you're using FormData to submit your file and other fields.

`fetch('/resume/experience', {
    method: 'POST',
    body: formData, 
})
.then(response => response.json())
.then(data => {
    console.log('Success:', data);
})
.catch(error => {
    console.error('Error:', error);
});`

**Comment by larrytamnjong** [comment]
@hastagAB I am sending form data in all cases, and I realized the issue is with using ```request.get_json()```. When I changed the function in the experience route to use ```request.form``` directly, it worked. The method ```request.get_json()``` throws a 415 error. You can read more about it here: [Flask Request Documentation](https://flask.palletsprojects.com/en/2.3.x/api/#flask.Request.data).

**Comment by hastagAB** [comment]
@larrytamnjong Ah okayy! I'm glad it worked.

**Pull request merged**
