### PR TITLE
Add flask-cors to requirements.txt

### PR DESCRIPTION
**Pull request by pvdosev**
Since we're now using flask-cors in the app, it should be in requirements.txt. This should also fix the test errors.

### CODE REVIEW

**Comment by yalsaffar** [comment]
I think the Pylint will take forever because the `vop` folder has all the site-packages files in it. I have added it to the `.gitignore` file in #62 PR.

**Comment by pvdosev** [comment]
Yeah, I also add it to .gitignore in another commit, along with removing the vor/ folder (which is just .venv)

**Comment by awilkescom** [comment]
@pvdosev can you review the test feedback? It looks like it refers to other updates, but if you could confirm that would be good.

**Comment by pvdosev** [comment]
Did the same thing in #69 instead

**Pull request closed without merging**
