### PR TITLE
Don't attempt to parse different request types: fixes adding new experiences

### LINKED ISSUE #60: Fix adding new experiences
It looks like adding a new experience section causes an error in the app, as the back end doesn't recieve the data properly. I'm working on debugging this.

### PR DESCRIPTION
**Pull request by pvdosev**
Closes #60

The check 
`if request.content_type == "multipart/form-data" else request.get_json()` 
doesn't work, because the content type in a multipart form data request also includes the separator between the data of the form, like "multipart/form-data; boundary=------------------------vqfqxmgyrMqVTDpDiq7JrB". This changes every request. 

Of course, we could parse it with some string separation, which would be pretty simple, but I thought I'd remove the json part completely since we aren't going to be accepting json data there anyway. I can re-add it if we think it's necessary, but I'd say it's easier and more straightforward like this. 

This pull request, if applied along with https://github.com/MLH-Fellowship/orientation-project-js-24.FAL.A/pull/24, makes the uploading of data work correctly.

### CODE REVIEW

**Comment by awilkescom** [comment]
Thanks @pvdosev - can you review the linter and test feedback?

**Comment by pvdosev** [comment]
Agh the test uses json

**Comment by pvdosev** [comment]
Hehe love a passing test

**Review by hastagAB — APPROVED** [review]
Looks good to me! 🚀

**Pull request merged**
