### PR TITLE
implement route for serving uploaded files from /uploads.

### PR DESCRIPTION
**Pull request by larrytamnjong**

### CODE REVIEW

**Comment by larrytamnjong** [comment]
@Pradyuman7

**Comment by Pradyuman7** [comment]
This makes sense, could you please create an issue for this and tag it to this PR so we know what was resolved and can accurately track it

**Review by Pradyuman7 — APPROVED** [review]
LGTM 💯 
Let's resolve the conflicts before merging the PR

**Comment by larrytamnjong** [comment]
> LGTM 💯 Let's resolve the conflicts before merging the PR

@Pradyuman7 conflict has been resolved :)

**Pull request merged**
